"""Prompt templates used by eXRage agents."""

from .orchestrator_prompts import ORCHESTRATOR_SYSTEM_PROMPT, ORCHESTRATOR_INPUT_PROMPT
from .planner_prompts import PLANNER_SYSTEM_PROMPT, PLANNER_INPUT_PROMPT
from .validator_prompts import VALIDATOR_SYSTEM_PROMPT, VALIDATOR_INPUT_PROMPT
from .executor_prompts import EXECUTOR_SYSTEM_PROMPT, EXECUTOR_INPUT_PROMPT_INITIAL, EXECUTOR_INPUT_PROMPT_REFINEMENT
from .asset_manager_prompts import ASSET_MANAGER_SYSTEM_PROMPT, ASSET_MANAGER_INPUT_PROMPT

__all__ = [
    "ORCHESTRATOR_SYSTEM_PROMPT",
    "ORCHESTRATOR_INPUT_PROMPT",
    "PLANNER_SYSTEM_PROMPT",
    "PLANNER_INPUT_PROMPT",
    "VALIDATOR_SYSTEM_PROMPT",
    "VALIDATOR_INPUT_PROMPT",
    "EXECUTOR_SYSTEM_PROMPT",
    "EXECUTOR_INPUT_PROMPT_INITIAL",
    "EXECUTOR_INPUT_PROMPT_REFINEMENT",
    "ASSET_MANAGER_SYSTEM_PROMPT",
    "ASSET_MANAGER_INPUT_PROMPT",
]
